//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAtencionClientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cola
    {
        public int IdCola { get; set; }
        public int IdTipoCola { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime HoraEntrada { get; set; }
        public System.DateTime FechaHoraAtencion { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoCola TipoCola { get; set; }
    }
}
