//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAtencionClientes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AtencionClientesEntities : DbContext
    {
        public AtencionClientesEntities()
            : base("name=AtencionClientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Cola> Colas { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<TipoCola> TipoColas { get; set; }
    
        [DbFunction("AtencionClientesEntities", "DeterminarColaMenorEspera")]
        public virtual IQueryable<DeterminarColaMenorEspera_Result> DeterminarColaMenorEspera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DeterminarColaMenorEspera_Result>("[AtencionClientesEntities].[DeterminarColaMenorEspera]()");
        }
    
        public virtual int ActualizarEstadosAtencion(Nullable<System.DateTime> fechaMomento)
        {
            var fechaMomentoParameter = fechaMomento.HasValue ?
                new ObjectParameter("FechaMomento", fechaMomento) :
                new ObjectParameter("FechaMomento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEstadosAtencion", fechaMomentoParameter);
        }
    }
}
